/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author carde
 */
public class VistaClienteOrg extends javax.swing.JFrame {

    /**
     * Creates new form VistaClienteOrg
     */
    public VistaClienteOrg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();

        jDialog1.setMinimumSize(new java.awt.Dimension(380, 380));
        jDialog1.getContentPane().setLayout(null);

        jButton6.setText("Añadir");
        jDialog1.getContentPane().add(jButton6);
        jButton6.setBounds(20, 280, 80, 32);

        jButton7.setText("Modificar");
        jDialog1.getContentPane().add(jButton7);
        jButton7.setBounds(100, 280, 90, 32);

        jButton8.setText("Eliminar");
        jDialog1.getContentPane().add(jButton8);
        jButton8.setBounds(200, 280, 80, 32);

        jButton9.setText("Volver");
        jDialog1.getContentPane().add(jButton9);
        jButton9.setBounds(280, 280, 80, 32);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jDialog1.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(40, 50, 280, 110);

        jLabel10.setText("Direcciones");
        jDialog1.getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 20, 70, 16);
        jDialog1.getContentPane().add(jFormattedTextField8);
        jFormattedTextField8.setBounds(190, 240, 150, 20);

        jLabel11.setText("Ciudad");
        jDialog1.getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 220, 120, 16);
        jDialog1.getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(40, 240, 130, 20);

        jLabel12.setText("Codigo Postal");
        jDialog1.getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 220, 90, 16);
        jDialog1.getContentPane().add(jFormattedTextField10);
        jFormattedTextField10.setBounds(40, 190, 290, 20);

        jLabel13.setText("Calle");
        jDialog1.getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 170, 40, 16);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 540));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 60, 610, 210);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(30, 340, 150, 20);

        jLabel1.setText("Codigo Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 320, 90, 16);
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(30, 290, 340, 20);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 270, 50, 16);
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(30, 400, 140, 20);

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(560, 330, 100, 20);

        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 290, 60, 16);
        getContentPane().add(jFormattedTextField6);
        jFormattedTextField6.setBounds(220, 340, 280, 20);

        jLabel6.setText("Representante");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 320, 90, 16);

        jLabel7.setText("Tipo Organizacion");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 380, 110, 16);

        jLabel8.setText("Numero Empleados");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 440, 120, 16);

        jButton1.setText("Añadir");
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 440, 67, 32);

        jButton2.setText("Modificar");
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 440, 83, 32);

        jButton3.setText("Eliminar");
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 440, 76, 32);

        jButton4.setText("Volver");
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 440, 66, 32);

        jButton5.setText("DIRECCIONES");
        getContentPane().add(jButton5);
        jButton5.setBounds(230, 390, 120, 30);

        jLabel14.setText("PERSONA JURIDICA");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 30, 120, 16);

        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        getContentPane().add(jFormattedTextField11);
        jFormattedTextField11.setBounds(30, 460, 150, 20);

        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        getContentPane().add(jFormattedTextField12);
        jFormattedTextField12.setBounds(560, 290, 100, 20);

        jFormattedTextField13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        getContentPane().add(jFormattedTextField13);
        jFormattedTextField13.setBounds(560, 310, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaClienteOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaClienteOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaClienteOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaClienteOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaClienteOrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JFormattedTextField jFormattedTextField1;
    public javax.swing.JFormattedTextField jFormattedTextField10;
    public javax.swing.JFormattedTextField jFormattedTextField11;
    public javax.swing.JFormattedTextField jFormattedTextField12;
    public javax.swing.JFormattedTextField jFormattedTextField13;
    public javax.swing.JFormattedTextField jFormattedTextField2;
    public javax.swing.JFormattedTextField jFormattedTextField4;
    public javax.swing.JFormattedTextField jFormattedTextField5;
    public javax.swing.JFormattedTextField jFormattedTextField6;
    public javax.swing.JFormattedTextField jFormattedTextField8;
    public javax.swing.JFormattedTextField jFormattedTextField9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
